name: epilepsy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  flutter_svg: ^0.20.0-nullsafety.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
  fl_chart: ^0.36.1
  intl: ^0.17.0
  permission_handler: ^5.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+22
  flutter_local_notifications: ^4.0.1+2
  # flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^1.8.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/epilepsy-logo.png
    - assets/images/epilepsy-logo.jpg
    - assets/images/dashboard.jpg
    - assets/images/calendar.jpg
    - assets/images/passport.jpg
    - assets/images/profile-001.jpg
    - assets/images/profile-001.png
    - assets/images/what_is_epilepsy.jpg
    - assets/images/cause-epilepsy.png
    - assets/images/type_of_epilepsy.gif
    - assets/images/rescure_of_epilepsy.jpg
    - assets/images/basic-cpr.jpg
    - assets/images/long-tem_rescue.jpg
    - assets/images/knowledge.jpg
    - assets/images/drug-pill.jpg
    - assets/images/back.svg
    - assets/images/info-bg.svg
    - assets/images/info-bg-2.svg
    - assets/images/drug_1.jpg
    - assets/images/drug_2.png
    - assets/images/drug_3.png
    - assets/images/drug_4.png
    - assets/images/drug_5.png
    - assets/images/drug_6.png
    - assets/images/drug_7.png
    - assets/images/drug_8.png
    - assets/images/drug_9.png
    - assets/images/drug_10.png
    - assets/images/drug_11.png
    - assets/images/drug_12.png
    - assets/images/drug_13.png
    - assets/images/drug_14.png
    - assets/images/about-logo.png
    - assets/images/line-id.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
